// Code generated by sqlc. DO NOT EDIT.
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (user_id, name, type, balance)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, type, balance, created_at, updated_at, deleted_at
`

func (q *Queries) CreateAccount(ctx context.Context, userID uuid.UUID, name string, accountType string, balance int64) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, userID, name, accountType, balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, user_id, name, type, balance, created_at, updated_at, deleted_at
FROM accounts
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountsByUserID = `-- name: ListAccountsByUserID :many
SELECT id, user_id, name, type, balance, created_at, updated_at, deleted_at
FROM accounts
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]Account, error) {
	rows, err := q.db.Query(ctx, listAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
SET name = $2,
    type = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, type, balance, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateAccount(ctx context.Context, id uuid.UUID, name string, accountType string) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, id, name, accountType)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteAccount = `-- name: SoftDeleteAccount :exec
UPDATE accounts
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteAccount, id)
	return err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :exec
UPDATE accounts
SET balance = balance + $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateAccountBalance(ctx context.Context, id uuid.UUID, delta int64) error {
	_, err := q.db.Exec(ctx, updateAccountBalance, id, delta)
	return err
}
