// Code generated by sqlc. DO NOT EDIT.
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (user_id, name, type)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, type, created_at, updated_at, deleted_at
`

func (q *Queries) CreateCategory(ctx context.Context, userID uuid.UUID, name string, categoryType string) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, userID, name, categoryType)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryByID = `-- name: GetCategoryByID :one
SELECT id, user_id, name, type, created_at, updated_at, deleted_at
FROM categories
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategoryByID, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCategoriesByUserID = `-- name: ListCategoriesByUserID :many
SELECT id, user_id, name, type, created_at, updated_at, deleted_at
FROM categories
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListCategoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
SET name = $2,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, type, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateCategory(ctx context.Context, id uuid.UUID, name string) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, id, name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteCategory = `-- name: SoftDeleteCategory :exec
UPDATE categories
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCategory(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteCategory, id)
	return err
}

const createDefaultCategories = `-- name: CreateDefaultCategories :exec
INSERT INTO categories (user_id, name, type) VALUES
    ($1, 'Salário', 'income'),
    ($1, 'Freelance', 'income'),
    ($1, 'Investimentos', 'income'),
    ($1, 'Outros (Receita)', 'income'),
    ($1, 'Alimentação', 'expense'),
    ($1, 'Transporte', 'expense'),
    ($1, 'Moradia', 'expense'),
    ($1, 'Saúde', 'expense'),
    ($1, 'Educação', 'expense'),
    ($1, 'Lazer', 'expense'),
    ($1, 'Outros (Despesa)', 'expense')
`

func (q *Queries) CreateDefaultCategories(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createDefaultCategories, userID)
	return err
}
