// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// User represents a row in the users table.
type User struct {
	ID             uuid.UUID          `json:"id"`
	Email          string             `json:"email"`
	PasswordHash   string             `json:"password_hash"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	CreatedAt      time.Time          `json:"created_at"`
	UpdatedAt      time.Time          `json:"updated_at"`
}

// GetFailedAttemptsRow is the result type for GetFailedAttempts query.
type GetFailedAttemptsRow struct {
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

// RefreshToken represents a row in the refresh_tokens table.
type RefreshToken struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

// Account represents a row in the accounts table.
type Account struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	Balance   int64              `json:"balance"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Category represents a row in the categories table.
type Category struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Name      string             `json:"name"`
	Type      string             `json:"type"`
	CreatedAt time.Time          `json:"created_at"`
	UpdatedAt time.Time          `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

// Transaction represents a row in the transactions table.
type Transaction struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	AccountID   uuid.UUID          `json:"account_id"`
	CategoryID  pgtype.UUID        `json:"category_id"`
	Type        string             `json:"type"`
	Amount      int64              `json:"amount"`
	Description string             `json:"description"`
	Date        pgtype.Date        `json:"date"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   time.Time          `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

// ListTransactionsParams holds the parameters for the ListTransactions query.
type ListTransactionsParams struct {
	UserID     uuid.UUID   `json:"user_id"`
	AccountID  pgtype.UUID `json:"account_id"`
	CategoryID pgtype.UUID `json:"category_id"`
	Type       pgtype.Text `json:"type"`
	DateFrom   pgtype.Date `json:"date_from"`
	DateTo     pgtype.Date `json:"date_to"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}
