// Code generated by sqlc. DO NOT EDIT.
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (user_id, account_id, category_id, type, amount, description, date)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, account_id, category_id, type, amount, description, date, created_at, updated_at, deleted_at
`

func (q *Queries) CreateTransaction(ctx context.Context, userID uuid.UUID, accountID uuid.UUID, categoryID pgtype.UUID, txType string, amount int64, description string, date pgtype.Date) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction, userID, accountID, categoryID, txType, amount, description, date)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, user_id, account_id, category_id, type, amount, description, date, created_at, updated_at, deleted_at
FROM transactions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTransactionByID(ctx context.Context, id uuid.UUID) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, user_id, account_id, category_id, type, amount, description, date, created_at, updated_at, deleted_at
FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND ($2::UUID IS NULL OR account_id = $2)
  AND ($3::UUID IS NULL OR category_id = $3)
  AND ($4::VARCHAR IS NULL OR type = $4)
  AND ($5::DATE IS NULL OR date >= $5)
  AND ($6::DATE IS NULL OR date <= $6)
ORDER BY date DESC, created_at DESC
LIMIT $7 OFFSET $8
`

func (q *Queries) ListTransactions(ctx context.Context, arg ListTransactionsParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactions,
		arg.UserID,
		arg.AccountID,
		arg.CategoryID,
		arg.Type,
		arg.DateFrom,
		arg.DateTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccountID,
			&i.CategoryID,
			&i.Type,
			&i.Amount,
			&i.Description,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET account_id = $2,
    category_id = $3,
    type = $4,
    amount = $5,
    description = $6,
    date = $7,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, account_id, category_id, type, amount, description, date, created_at, updated_at, deleted_at
`

func (q *Queries) UpdateTransaction(ctx context.Context, id uuid.UUID, accountID uuid.UUID, categoryID pgtype.UUID, txType string, amount int64, description string, date pgtype.Date) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction, id, accountID, categoryID, txType, amount, description, date)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.CategoryID,
		&i.Type,
		&i.Amount,
		&i.Description,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTransaction, id)
	return err
}
