// Code generated by sqlc. DO NOT EDIT.
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, password_hash, failed_attempts, locked_until, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, email string, passwordHash string) (User, error) {
	row := q.db.QueryRow(ctx, createUser, email, passwordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, failed_attempts, locked_until, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, failed_attempts, locked_until, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FailedAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedAttempts = `-- name: IncrementFailedAttempts :exec
UPDATE users
SET failed_attempts = failed_attempts + 1,
    locked_until = CASE
        WHEN failed_attempts + 1 >= 5 THEN NOW() + INTERVAL '15 minutes'
        ELSE locked_until
    END,
    updated_at = NOW()
WHERE email = $1
`

func (q *Queries) IncrementFailedAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, incrementFailedAttempts, email)
	return err
}

const resetFailedAttempts = `-- name: ResetFailedAttempts :exec
UPDATE users
SET failed_attempts = 0,
    locked_until = NULL,
    updated_at = NOW()
WHERE email = $1
`

func (q *Queries) ResetFailedAttempts(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, resetFailedAttempts, email)
	return err
}

const getFailedAttempts = `-- name: GetFailedAttempts :one
SELECT failed_attempts, locked_until
FROM users
WHERE email = $1
`

func (q *Queries) GetFailedAttempts(ctx context.Context, email string) (GetFailedAttemptsRow, error) {
	row := q.db.QueryRow(ctx, getFailedAttempts, email)
	var i GetFailedAttemptsRow
	err := row.Scan(&i.FailedAttempts, &i.LockedUntil)
	return i, err
}
