// Package docs Code generated by swag. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "REST API de rastreamento de finanças pessoais. Gerencie contas, categorias, transações e visualize resumos financeiros.",
        "title": "FinTrack API",
        "contact": {},
        "version": "1.0"
    },
    "host": "localhost:8080",
    "basePath": "/api/v1",
    "paths": {
        "/auth/register": {
            "post": {
                "description": "Cria um novo usuário com email e senha",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Registrar novo usuário",
                "parameters": [
                    {
                        "description": "Dados de registro",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": {"type": "string", "example": "usuario@email.com"},
                                "password": {"type": "string", "minLength": 8, "maxLength": 72, "example": "senhaSegura123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Usuário criado",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "id": {"type": "string", "format": "uuid"},
                                "email": {"type": "string"},
                                "created_at": {"type": "string", "format": "date-time"}
                            }
                        }
                    },
                    "409": {"description": "Email já existe"},
                    "422": {"description": "Dados inválidos"}
                }
            }
        },
        "/auth/login": {
            "post": {
                "description": "Autentica o usuário e retorna tokens JWT",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Login",
                "parameters": [
                    {
                        "description": "Credenciais",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["email", "password"],
                            "properties": {
                                "email": {"type": "string", "example": "usuario@email.com"},
                                "password": {"type": "string", "example": "senhaSegura123"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Token pair",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {"type": "string"},
                                "refresh_token": {"type": "string"}
                            }
                        }
                    },
                    "401": {"description": "Credenciais inválidas"},
                    "422": {"description": "Campos obrigatórios ausentes"},
                    "429": {"description": "Muitas tentativas, tente novamente depois"}
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Renova os tokens usando um refresh token válido",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Auth"],
                "summary": "Renovar tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["refresh_token"],
                            "properties": {
                                "refresh_token": {"type": "string"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Novo token pair",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "access_token": {"type": "string"},
                                "refresh_token": {"type": "string"}
                            }
                        }
                    },
                    "401": {"description": "Refresh token inválido ou expirado"}
                }
            }
        },
        "/accounts": {
            "get": {
                "security": [{"BearerAuth": []}],
                "description": "Retorna todas as contas do usuário autenticado",
                "produces": ["application/json"],
                "tags": ["Accounts"],
                "summary": "Listar contas",
                "responses": {
                    "200": {"description": "Lista de contas"}
                }
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "description": "Cria uma nova conta financeira",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Accounts"],
                "summary": "Criar conta",
                "parameters": [
                    {
                        "description": "Dados da conta",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name", "type"],
                            "properties": {
                                "name": {"type": "string", "minLength": 1, "maxLength": 100},
                                "type": {"type": "string", "enum": ["checking", "savings", "credit_card", "cash", "investment"]},
                                "initial_balance": {"type": "integer", "description": "Saldo inicial em centavos"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Conta criada"},
                    "422": {"description": "Dados inválidos"}
                }
            }
        },
        "/accounts/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Accounts"],
                "summary": "Atualizar conta",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true},
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name", "type"],
                            "properties": {
                                "name": {"type": "string"},
                                "type": {"type": "string", "enum": ["checking", "savings", "credit_card", "cash", "investment"]}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Conta atualizada"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Conta não encontrada"},
                    "422": {"description": "Dados inválidos"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Accounts"],
                "summary": "Excluir conta",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "Conta excluída"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Conta não encontrada"}
                }
            }
        },
        "/categories": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Categories"],
                "summary": "Listar categorias",
                "responses": {"200": {"description": "Lista de categorias"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Categories"],
                "summary": "Criar categoria",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name", "type"],
                            "properties": {
                                "name": {"type": "string", "minLength": 1, "maxLength": 50},
                                "type": {"type": "string", "enum": ["income", "expense"]}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Categoria criada"},
                    "422": {"description": "Dados inválidos"}
                }
            }
        },
        "/categories/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Categories"],
                "summary": "Atualizar categoria",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true},
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["name"],
                            "properties": {"name": {"type": "string"}}
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Categoria atualizada"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Não encontrada"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Categories"],
                "summary": "Excluir categoria",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "Excluída"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Não encontrada"}
                }
            }
        },
        "/transactions": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Transactions"],
                "summary": "Listar transações",
                "parameters": [
                    {"type": "string", "name": "account_id", "in": "query"},
                    {"type": "string", "name": "category_id", "in": "query"},
                    {"type": "string", "name": "type", "in": "query", "enum": ["income", "expense"]},
                    {"type": "string", "name": "date_from", "in": "query", "description": "YYYY-MM-DD"},
                    {"type": "string", "name": "date_to", "in": "query", "description": "YYYY-MM-DD"},
                    {"type": "integer", "name": "limit", "in": "query", "default": 20},
                    {"type": "integer", "name": "offset", "in": "query", "default": 0}
                ],
                "responses": {"200": {"description": "Lista de transações"}}
            },
            "post": {
                "security": [{"BearerAuth": []}],
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Transactions"],
                "summary": "Criar transação",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["amount", "type", "account_id", "date"],
                            "properties": {
                                "amount": {"type": "number", "description": "Valor positivo com até 2 casas decimais"},
                                "type": {"type": "string", "enum": ["income", "expense"]},
                                "account_id": {"type": "string", "format": "uuid"},
                                "category_id": {"type": "string", "format": "uuid"},
                                "description": {"type": "string"},
                                "date": {"type": "string", "format": "date", "example": "2024-01-15"}
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {"description": "Transação criada"},
                    "403": {"description": "Conta/categoria não pertence ao usuário"},
                    "404": {"description": "Conta/categoria não encontrada"},
                    "422": {"description": "Dados inválidos"}
                }
            }
        },
        "/transactions/{id}": {
            "put": {
                "security": [{"BearerAuth": []}],
                "tags": ["Transactions"],
                "summary": "Atualizar transação",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true},
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "required": ["amount", "type", "account_id", "date"],
                            "properties": {
                                "amount": {"type": "number"},
                                "type": {"type": "string", "enum": ["income", "expense"]},
                                "account_id": {"type": "string", "format": "uuid"},
                                "category_id": {"type": "string", "format": "uuid"},
                                "description": {"type": "string"},
                                "date": {"type": "string", "format": "date"}
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {"description": "Transação atualizada"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Não encontrada"}
                }
            },
            "delete": {
                "security": [{"BearerAuth": []}],
                "tags": ["Transactions"],
                "summary": "Excluir transação",
                "parameters": [
                    {"type": "string", "format": "uuid", "name": "id", "in": "path", "required": true}
                ],
                "responses": {
                    "204": {"description": "Excluída"},
                    "403": {"description": "Acesso negado"},
                    "404": {"description": "Não encontrada"}
                }
            }
        },
        "/summary": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Summary"],
                "summary": "Resumo financeiro por período",
                "parameters": [
                    {"type": "string", "name": "date_from", "in": "query", "required": true, "description": "YYYY-MM-DD"},
                    {"type": "string", "name": "date_to", "in": "query", "required": true, "description": "YYYY-MM-DD"}
                ],
                "responses": {
                    "200": {
                        "description": "Resumo",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "total_income": {"type": "integer"},
                                "total_expense": {"type": "integer"},
                                "net_balance": {"type": "integer"}
                            }
                        }
                    },
                    "422": {"description": "Parâmetros inválidos"}
                }
            }
        },
        "/summary/categories": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Summary"],
                "summary": "Resumo por categoria",
                "parameters": [
                    {"type": "string", "name": "date_from", "in": "query", "required": true, "description": "YYYY-MM-DD"},
                    {"type": "string", "name": "date_to", "in": "query", "required": true, "description": "YYYY-MM-DD"}
                ],
                "responses": {
                    "200": {"description": "Resumo por categoria"},
                    "422": {"description": "Parâmetros inválidos"}
                }
            }
        },
        "/summary/trend": {
            "get": {
                "security": [{"BearerAuth": []}],
                "tags": ["Summary"],
                "summary": "Tendência mensal",
                "parameters": [
                    {"type": "integer", "name": "year", "in": "query", "required": true, "description": "Ano (2000-2100)"}
                ],
                "responses": {
                    "200": {"description": "12 meses de dados"},
                    "422": {"description": "Ano inválido"}
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header",
            "description": "Digite: Bearer {access_token}"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "FinTrack API",
	Description:      "REST API de rastreamento de finanças pessoais",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
